# Starter pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'valurban4/brief-8'
    command: 'buildAndPush'
    Dockerfile: '**valurban4/brief-8:latest'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    namespace: 'qal'
    strategy: 'canary'
    percentage: '0'
    manifests: 'manifest.yml'