apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp
  labels:
    app: vote-app
spec:
  selector:
    matchLabels:
      app: vote-app
  replicas: 2
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: voteapp
        image: valurban4/brief-8:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: "0.5"
        env:
        - name: REDIS
          value: "clusteredis"
        - name: STRESS_SECS
          value: "2"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis
              key: nm-password
---
apiVersion: v1
kind: Service
metadata:
  name: voteapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: vote-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          args: ["--requirepass", "$(REDIS_PWD)"]
          env:
            - name: REDIS_PWD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: nm-password
          volumeMounts:
            - name: diskredis
              mountPath: /data
      volumes:
        - name: diskredis
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clusteredis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingressvote
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
# spec:
#   rules:
#   - http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: voteapp
#             port:
#               number: 80
# ---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scaleapp
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voteapp
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 5Gi
